# Generated by Django 6.0 on 2025-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.CharField(
                choices=[
                    ("pizza", "Pizza"),
                    ("burger", "Burger"),
                    ("indian", "Indian"),
                    ("chinese", "Chinese"),
                    ("dessert", "Dessert"),
                ],
                default="pizza",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="food",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
