# Generated by Django 6.0 on 2025-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_food_category_food_rating_alter_food_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="foods/"),
        ),
    ]
